### ISSUE TITLE
dataproc.v1.Cluster fails to update with bad request

### ISSUE THREAD

**Issue by ColeSiegelTR** [pulumi/pulumi-google-native#254]
When I try to increase the number of worker nodes from 2 to 3 it now registers as an `update` instead of a `replace` but the request fails with a `400` error. It seems like maybe `updateMask` noted here is not being set https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters/patch

```
     Type                                                       Name                                                                         Plan       Info
 ~   ├─ google-native:dataproc/v1:Cluster                       dp_cluster                                                                   update     [diff: +config]
 
Resources:
    ~ 1 to update

Do you want to perform this update? yes
Updating:
     Type                                                       Name                                                                         Status                  Info
 ~   └─ google-native:dataproc/v1:Cluster                       dp_cluster                                                                   **updating failed**     [diff: +config
 
Diagnostics:
    error: update failed
 
  google-native:dataproc/v1:Cluster (dp_cluster):
    error: error sending request: googleapi: Error 400: Request must specify update_mask with at least one path.:
```

**Comment by mikhailshilkov** [comment]
Similar to #95 - I guess the fix would be similar

**Comment by lblackstone** [comment]
This should be fixed by https://github.com/pulumi/pulumi-google-native/pull/386

**Comment by viveklak** [comment]
As per https://github.com/pulumi/pulumi-google-native/pull/386#issuecomment-1087641534
the issue isn't fixed for some resources which require nested properties highlighted in the updateMask.
